import java.util.List;
import javax.swing.table.DefaultTableModel;

// Agenda View:
// Gerencia a parte visual do programa, não sabe nada lógico

public class AgendaView extends javax.swing.JPanel {
    
    /**
     * Creates new form AgendaView
     */
    public AgendaView() {
        initComponents();
    }
    
    public void atualizarTabela(List<Contato> contatos) {
    DefaultTableModel modeloTabela = (DefaultTableModel) tabelaContatos.getModel();

    modeloTabela.setRowCount(0); // limpa antes de popular, senão duplica

    for (Contato c : contatos) {
        modeloTabela.addRow(new Object[]{
            c.getId(), c.getNome(), c.getTelefone(), c.getEmail()
        });
    }
}
    
    public int getIdSelecionado() {
        int row = tabelaContatos.getSelectedRow();
        if (row == -1) return -1;
        return (int) tabelaContatos.getModel().getValueAt(row, 0);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelSuperior = new javax.swing.JPanel();
        scrollPanel = new javax.swing.JScrollPane();
        tabelaContatos = new javax.swing.JTable();
        panelInferior = new javax.swing.JPanel();
        campoBusca = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        btnAdicionar = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnRemover = new javax.swing.JButton();

        setLayout(new java.awt.BorderLayout(2, 2));

        panelSuperior.setLayout(new javax.swing.BoxLayout(panelSuperior, javax.swing.BoxLayout.PAGE_AXIS));

        tabelaContatos.setAutoCreateRowSorter(true);
        tabelaContatos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null}
            },
            new String [] {
                "id", "nome", "telefone", "email"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabelaContatos.setToolTipText("");
        tabelaContatos.setColumnSelectionAllowed(true);
        tabelaContatos.setShowGrid(true);
        scrollPanel.setViewportView(tabelaContatos);
        tabelaContatos.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

        panelSuperior.add(scrollPanel);

        campoBusca.setColumns(16);
        campoBusca.setToolTipText("");
        panelInferior.add(campoBusca);

        btnBuscar.setText("Buscar");
        btnBuscar.setToolTipText("Busca um contato");
        panelInferior.add(btnBuscar);

        btnAdicionar.setText("Adicionar");
        btnAdicionar.setToolTipText("Adiciona um contato");
        panelInferior.add(btnAdicionar);

        btnEditar.setText("Editar");
        btnEditar.setToolTipText("Edita um contato");
        btnEditar.setEnabled(false);
        panelInferior.add(btnEditar);

        btnRemover.setText("Remover");
        btnRemover.setToolTipText("Remove um contato");
        btnRemover.setEnabled(false);
        panelInferior.add(btnRemover);

        panelSuperior.add(panelInferior);

        add(panelSuperior, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    // Getters e Setters
    public javax.swing.JTextField getCampoBusca() {
        return campoBusca;
    }

    public javax.swing.JTable getTabelaContatos() {
        return tabelaContatos;
    }

    public javax.swing.JButton getBtnAdicionar() {
        return btnAdicionar;
    }

    public javax.swing.JButton getBtnBuscar() {
        return btnBuscar;
    }

    public javax.swing.JButton getBtnEditar() {
        return btnEditar;
    }

    public javax.swing.JButton getBtnRemover() {
        return btnRemover;
    }
    
    // Setters
    public void setTabelaContatos(javax.swing.JTable tabelaContatos) {
        this.tabelaContatos = tabelaContatos;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdicionar;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnRemover;
    private javax.swing.JTextField campoBusca;
    private javax.swing.JPanel panelInferior;
    private javax.swing.JPanel panelSuperior;
    private javax.swing.JScrollPane scrollPanel;
    private javax.swing.JTable tabelaContatos;
    // End of variables declaration//GEN-END:variables

}
