// Contato Dialog:
// Representa a caixa de dialogo de contato,
// usado para inserir dados de contato

public class ContatoDialog extends javax.swing.JDialog {

    private boolean confirmado = false;
    private final Contato contato;
    
    /**
     * Creates new form ContatoDialog
     */
    public ContatoDialog(javax.swing.JPanel pai, Contato contato) {
        super(javax.swing.SwingUtilities.getWindowAncestor(pai),
                contato == null ? "Novo Contato" : "Editar Contato",
                java.awt.Dialog.ModalityType.APPLICATION_MODAL);
        this.contato = contato;
        
        initComponents();
        setLocationRelativeTo(pai);
        
        if (contato != null) {
            txtNome.setText(contato.getNome());
            txtTelefone.setText(contato.getTelefone());
            txtEmail.setText(contato.getEmail());
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelPrincipal = new javax.swing.JPanel();
        panelSuperior = new javax.swing.JPanel();
        lblNome = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        lblTelefone = new javax.swing.JLabel();
        txtTelefone = new javax.swing.JTextField();
        lblEmail = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        panelInferior = new javax.swing.JPanel();
        btnSalvar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle(contato == null ? "Novo Contato" : "Editar Contato");
        setAlwaysOnTop(true);
        setLocation(new java.awt.Point(0, 0));
        setResizable(false);
        getContentPane().setLayout(new java.awt.BorderLayout(2, 2));

        panelPrincipal.setLayout(new javax.swing.BoxLayout(panelPrincipal, javax.swing.BoxLayout.PAGE_AXIS));

        panelSuperior.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.TRAILING, 10, 10));

        lblNome.setText("Nome: ");
        panelSuperior.add(lblNome);

        txtNome.setColumns(10);
        panelSuperior.add(txtNome);

        lblTelefone.setText("Telefone: ");
        panelSuperior.add(lblTelefone);

        txtTelefone.setColumns(10);
        panelSuperior.add(txtTelefone);

        lblEmail.setText("Email: ");
        panelSuperior.add(lblEmail);

        txtEmail.setColumns(10);
        panelSuperior.add(txtEmail);

        panelPrincipal.add(panelSuperior);

        panelInferior.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 10, 10));

        btnSalvar.setText("Salvar");
        btnSalvar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnSalvar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        panelInferior.add(btnSalvar);

        btnCancelar.setText("Cancelar");
        btnCancelar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCancelar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        panelInferior.add(btnCancelar);

        panelPrincipal.add(panelInferior);

        getContentPane().add(panelPrincipal, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents
   
    // Getters e Setters
    public boolean isConfirmado() { 
        return confirmado; 
    }
    
    public void setConfirmado(boolean confirmado) {
        this.confirmado = confirmado;
    }
    
    public String getNome() { 
        return txtNome.getText().trim(); 
    }
    
    public String getTelefone() { 
        return txtTelefone.getText().trim(); 
    }
    
    public String getEmail() { 
        return txtEmail.getText().trim(); 
    }
    
    public Contato getContato() { 
        return contato; 
    }
    
    public javax.swing.JButton getBtnCancelar() {
        return btnCancelar;
    }

    public javax.swing.JButton getBtnSalvar() {
        return btnSalvar;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblTelefone;
    private javax.swing.JPanel panelInferior;
    private javax.swing.JPanel panelPrincipal;
    private javax.swing.JPanel panelSuperior;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtTelefone;
    // End of variables declaration//GEN-END:variables
}
